version: '3.3'
services:
  db:
    container_name: "db"
    image: postgres:13.0-alpine
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  app:
    container_name: "app"
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code/
    env_file:
      - ./.env
    command: bash -c "cd /code && alembic upgrade head && python main.py"
    ports:
      - 80:8000
    depends_on:
      - db

volumes:
    db_data:
